package com.jpdev.main.domain

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable

@DynamoDBTable(tableName = "Idempotency")
class Idempotency {

    private String id
    private String encryptedBody

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    void setId(String id) {
        this.id = id
    }

    String getEncryptedBody() {
        return encryptedBody
    }

    void setEncryptedBody(String encryptedBody) {
        this.encryptedBody = encryptedBody
    }
}
